// ============================================================
// siteData.ts — AUTO-GENERATED by site_generator.py
// Do not edit manually. Re-run the generator to update.
// ============================================================

export type Variant = 'A' | 'B' | 'C' | 'D'

export interface ServiceItem {
  iconName: string
  name: string
  description: string
}

export interface ReviewItem {
  name: string
  rating: number
  text: string
  date: string
}

export interface WhyUsPoint {
  heading: string
  body: string
}

export interface ProcessStep {
  heading: string
  body: string
}

export interface FAQItem {
  question: string
  answer: string
}

export interface SiteData {
  businessName: string
  instagramUrl?: string
  facebookUrl?: string
  trade: string
  tagline: string
  phone: string
  email: string
  address: string
  city: string
  serviceArea: string
  googleBusinessUrl: string
  yearsExperience: number
  bookingUrl?: string
  logoUrl?: string
  photos: string[]
  variant: Variant
  hero: {
    heading: string
    subheading: string
    primaryCta: string
    secondaryCta: string
  }
  services: ServiceItem[]
  trustItems: string[]
  whyUs: {
    heading: string
    subheading: string
    points: WhyUsPoint[]
  }
  process: ProcessStep[]
  faqs: FAQItem[]
  about: {
    heading: string
    body: string
    ownerName: string
  }
  reviews: ReviewItem[]
  seo: {
    title: string
    description: string
    canonicalUrl: string
  }
}

const siteData: SiteData = {
  businessName: 'GAP Roofing Services Ltd',
  trade: 'Roofers',
  tagline: 'Manchester\'s Trusted Roofing Specialists',
  phone: '+44 161 850 0602',
  email: 'jobs@gaproofing.co.uk',
  address: '125-133 Pollard St, Manchester M4 7JB, United Kingdom',
  city: 'Manchester',
  serviceArea: 'Manchester',
  googleBusinessUrl: 'https://www.google.com/maps/search/?api=1&query=GAP%20Roofing%20Services%20Ltd&query_place_id=ChIJaRM8lN2le0gRogE-B9KC_4U',
  instagramUrl: 'https://www.instagram.com/aiwithdennis',
  facebookUrl: 'https://www.facebook.com/leadplug/',
  yearsExperience: 18,
  logoUrl: 'https://gaproofing.co.uk/apple-icon-57x57.png',
  photos: ["https://gaproofing.co.uk/ext/clients/high-res/_xl/142010/DJI_0656.png", "https://gaproofing.co.uk/ext/img/news_assets/_lg/142962/testing_2022-07-29-094253_osbb.webp", "https://gaproofing.co.uk/ext/img/news_assets/_lg/143053/DJI_0653.webp", "https://gaproofing.co.uk/ext/img/entry_assets/_lg/1715/cut-edge-1.webp", "https://gaproofing.co.uk/ext/img/news_assets/_lg/145145/DJI_0652_2022-08-11-094906_sbbm.webp", "https://gaproofing.co.uk/ext/img/news_assets/_lg/46859/IMG-20200629-WA0019.webp", "https://gaproofing.co.uk/ext/img/news_assets/_lg/146103/DJI_0413.webp", "https://gaproofing.co.uk/ext/img/news_assets/_lg/180622/National-Library-Wales-EPDM.webp"],

  variant: 'C',

  hero: {
    heading: 'Professional Roofers Serving Manchester and Surrounding Areas',
    subheading: 'GAP Roofing Services Ltd provides reliable roofing solutions throughout Manchester. Our skilled team delivers quality workmanship with complete transparency, ensuring your property stays protected in all weather conditions.',
    primaryCta: 'Get a Free Quote',
    secondaryCta: 'Call Now',
  },

  services: [
    {
      iconName: 'Roof',
      name: 'Roof Repairs',
      description: 'We fix leaks, damaged tiles, and structural issues quickly and effectively. Our repairs are built to last and come with full peace of mind.',
    },
    {
      iconName: 'RefreshCw',
      name: 'Roof Replacement',
      description: 'Complete roof replacements using quality materials and proven techniques. We handle everything from planning to cleanup, ensuring minimal disruption to your daily routine.',
    },
    {
      iconName: 'Droplets',
      name: 'Guttering Services',
      description: 'Professional gutter installation, repair, and cleaning to protect your property from water damage. We ensure proper drainage and long-lasting performance.',
    },
    {
      iconName: 'Shield',
      name: 'Roof Maintenance',
      description: 'Regular inspections and preventative maintenance to extend your roof\'s lifespan. We identify potential problems early, saving you money on costly repairs.',
    },
    {
      iconName: 'Home',
      name: 'Flat Roofing',
      description: 'Specialist flat roof installation and repair using modern materials and techniques. Perfect for commercial properties and residential extensions.',
    },
    {
      iconName: 'Search',
      name: 'Roof Inspections',
      description: 'Thorough roof surveys to assess condition and identify any issues. We provide detailed reports with clear recommendations and honest pricing.',
    },
  ],

  trustItems: [
    'Fully Insured',
    'Free Quotes',
    'Local to Manchester',
    'Work Guaranteed'
  ],

  whyUs: {
    heading: 'Why Choose GAP Roofing Services Ltd?',
    subheading: 'We\'re a local Manchester roofing company committed to delivering honest, reliable service at fair prices.',
    points: [
      {
        heading: 'Local Knowledge',
        body: 'As Manchester locals, we understand the weather challenges your roof faces. We use materials and techniques proven to work in our climate.',
      },
      {
        heading: 'Transparent Pricing',
        body: 'No hidden costs or surprise charges. We provide clear, detailed quotes so you know exactly what you\'re paying for.',
      },
      {
        heading: 'Quality Materials',
        body: 'We only use high-grade materials from trusted suppliers. This ensures your roof stands up to Manchester\'s unpredictable weather.',
      },
      {
        heading: 'Reliable Service',
        body: 'We turn up when we say we will and complete work on time. Your project matters to us as much as it does to you.',
      },
    ],
  },

  process: [
    {
      heading: 'Contact Our Team',
      body: 'Call us or request a quote online. We\'ll arrange a convenient time to visit your property and assess your roofing needs.',
    },
    {
      heading: 'Free Survey',
      body: 'We carry out a thorough inspection and provide you with a detailed, no-obligation quote. All our surveys are completely free with no strings attached.',
    },
    {
      heading: 'Expert Installation',
      body: 'Our skilled roofers complete your project using quality materials and proven techniques. We keep you informed throughout the process.',
    },
    {
      heading: 'Final Inspection',
      body: 'We conduct a final check to ensure everything meets our high standards. Your property is left clean and tidy, ready to enjoy.',
    },
  ],

  faqs: [
    {
      question: 'How quickly can you provide a quote?',
      answer: 'We typically arrange surveys within 24-48 hours of your initial contact. Once we\'ve inspected your roof, we\'ll provide a detailed quote the same day or within 24 hours.',
    },
    {
      question: 'Do you work in all weather conditions?',
      answer: 'Safety is our priority, so we don\'t work during severe weather conditions. However, we can carry out emergency repairs in most conditions and will schedule full work for suitable weather windows.',
    },
    {
      question: 'What areas of Manchester do you cover?',
      answer: 'We serve Manchester and all surrounding areas. Our local knowledge means we\'re familiar with the building styles and weather challenges throughout the region.',
    },
    {
      question: 'Are you fully insured?',
      answer: 'Yes, we carry comprehensive public liability insurance and employers\' liability cover. We\'re happy to provide proof of insurance before starting any work on your property.',
    },
    {
      question: 'Do you clean up after completing work?',
      answer: 'Absolutely. We take pride in leaving your property clean and tidy. All debris is removed and the area around your home is thoroughly cleaned before we consider the job complete.',
    },
    {
      question: 'Can you help with insurance claims?',
      answer: 'We have experience working with insurance companies and can provide detailed reports and quotes to support your claim. We\'ll work with your insurer to ensure the process goes as smoothly as possible.',
    },
  ],

  about: {
    heading: 'About GAP Roofing Services Ltd',
    body: 'I started GAP Roofing Services because I believe every Manchester home and business deserves a roof they can rely on. Our focus is on honest advice, quality workmanship, and treating every property as if it were our own. We\'re proud to serve our local community with the reliable roofing services they deserve.',
    ownerName: 'The GAP Roofing Team — Owner',
  },

  reviews: [
    {
      name: 'Robert f.',
      rating: 5,
      text: 'Very Good Service recommended',
      date: '',
    },
    {
      name: 'Jason T.',
      rating: 5,
      text: 'Great place get guttering 👍',
      date: '',
    },
  ],

  seo: {
    title: 'GAP Roofing Services Ltd | Roofers in Manchester',
    description: 'Professional roofers in Manchester. Roof repairs, replacements & maintenance. Fully insured, free quotes, quality guaranteed. Call +44 161 850 0602 today.',
    canonicalUrl: 'https://preview-gap-roofing-services-ltd.vercel.app',
  },
}

export default siteData

// CSS custom properties injected by site_generator.py
// These override :root variables in index.css at runtime
export const siteTheme = {
  '--color-primary':  '#1B2D45',
  '--color-accent':   '#E85D26',
  '--color-bg':       '#FAFAF8',
  '--color-text':     '#1A1A1A',
  '--color-muted':    '#6B7280',
  '--color-border':   '#E5E5E5',
  '--font-heading':   "'Instrument Serif', Georgia, serif",
  '--font-body':      "'DM Sans', system-ui, sans-serif",
}
